
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 14 08:43:26 CST 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int fcjs = 13;
  public static final int ruta = 10;
  public static final int dir = 16;
  public static final int enc = 5;
  public static final int EOF = 0;
  public static final int ena = 4;
  public static final int hc = 3;
  public static final int comilla = 12;
  public static final int ha = 2;
  public static final int cjs = 8;
  public static final int ccss = 9;
  public static final int error = 1;
  public static final int pc = 15;
  public static final int fccss = 14;
  public static final int cierra = 7;
  public static final int abre = 6;
  public static final int igual = 11;
}

